# language: node_js
# node_js:
#   - '8'
# branches:
#   only:
#     - master
# before_install:
#   - npm install -g hexo-cli
# before_script:
#   - git config user.name "${GH_NAME}"
#   - git config user.email "${GH_EMAIL}"
#   - sed -i'' "s~https://github.com/${GH_NAME}/happycoder-blog-site.git~https://${GH_TOKEN}@github.com/${GH_NAME}/happycoder-blog-site.git~" _config.yml
# script:
#   - hexo g
#   - hexo d
language: node_js
sudo: required
node_js:
  - 7.9.0
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "${GH_NAME}"
  - git config user.email "${GH_EMAIL}"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle
